default_context:
  name: "s3mart"
  version: "0.1.0"
  slug: "s3mart"
  command: "s3mart"
  cli: "argparse"
  config: "y"
  compat: "bpyutils"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "A meta-analysis for meat across geographies."
  author: "Rebecca Furbeck, Achilles Rasquinha"
  email: "rafurbeck@gmail.com"
  keywords: "meta analysis geo meat"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "s3mart"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "s3mart"
  github_action: "n"
  ml: "y"
  editor: "vscode"
  url: "1"