default_context:
  name: "geomeat"
  version: "0.1.0"
  slug: "geomeat"
  command: "geomeat"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "A meta-analysis for meat across geographies."
  author: "Rebecca Furbeck, Achilles Rasquinha"
  email: "rafurbeck@gmail.como"
  keywords: "meta analysis geo meat"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "geomeat"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "geomeat"
  github_action: "n"
  ml: "y"
  editor: "vscode"
  url: "1"