default_context:
  name: "s3mart"
  version: "0.1.0"
  slug: "s3mart"
  command: "s3mart"
  cli: "argparse"
  config: "y"
  compat: "bpyutils"
  jupyter: "n"
  sqlite: "n"
  pypy: "y"
  description: ""
  author: ""
  email: ""
  keywords: ""
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: ""
  repo_service_reponame: "s3mart"
  docker_service_username: ""
  docker_service_reponame: "s3mart"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com//s3mart"