name: Model CI

on: [push, pull_request]

env:
  # ci variables
  SRA_TOOLKIT_VERSION: "2.9.6"
  TRIM_GALORE_VERSION: "0.6.6"
  # package variables
  PIP_ARGS: "--use-deprecated=legacy-resolver"
  GEOMEAT_JOBS: 16
  GEOMEAT_DATA_DIR: "$HOME/data"
  # system variables

jobs:
  train:
    name: Train
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/achillesrasquinha/dl

    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Install dependencies
        run: |
          wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/$SRA_TOOLKIT_VERSION/sratoolkit.$SRA_TOOLKIT_VERSION-ubuntu64.tar.gz -O $HOME/sra-toolkit.tar.gz
          tar xzvf $HOME/sra-toolkit.tar.gz -C $HOME
          cp -R $HOME/sratoolkit.$SRA_TOOLKIT_VERSION-ubuntu64/bin/* /usr/local/bin

          wget https://raw.githubusercontent.com/ncbi/ncbi-vdb/master/libs/kfg/default.kfg -P $HOME/.ncbi
          export VDB_CONFIG=$HOME/.ncbi/default.kfg

          echo "/repository/user/main/public/root = \"GEOMEAT_DATA_DIR\"" >> $VDB_CONFIG

          apt-get update && apt-get install -y --no-install-recommends fastqc

          wget https://github.com/FelixKrueger/TrimGalore/archive/$TRIM_GALORE_VERSION.tar.gz -O $HOME/trim-galore.tar.gz
          tar xvzf $HOME/trim-galore.tar.gz

          pip install -r requirements-dev.txt
          python setup.py develop
      - name: Run Pipeline
        run: |
          bpyutils -m geomeat.data.get_data
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: multiqc-output
          path: $GEOMEAT_DATA_DIR/multiqc_report.html