name: Model CI

on: [push, pull_request]

env:
  SRA_TOOLKIT_VERSION: "2.11.2"
  PIP_ARGS: "--use-deprecated=legacy-resolver"

jobs:
  train:
    name: Train
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/achillesrasquinha/dl

    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Install dependencies
        run: |
          wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/$SRA_TOOLKIT_VERSION/sratoolkit.$SRA_TOOLKIT_VERSION-ubuntu64.tar.gz -O $HOME/sra-toolkit.tar.gz
          tar xzvf $HOME/sra-toolkit.tar.gz -C $HOME
          export PATH=$PATH:$HOME/sratoolkit.$SRA_TOOLKIT_VERSION-ubuntu64/bin

          wget https://raw.githubusercontent.com/ncbi/ncbi-vdb/master/libs/kfg/default.kfg -P $HOME/.ncbi
          
          export VDB_CONFIG=$HOME/.ncbi/default.kfg

          vdb-config --restore-defaults

          vdb-config -i & read -t 3; kill $!

          fasterq-dump -h

          pip install -r requirements-dev.txt
          python setup.py develop
      - name: Run Pipeline
        run: |
          bpyutils -m geomeat.data.get_data