name: Model CI

on: [push, pull_request]

env:
  # ci variables
  SRA_TOOLKIT_VERSION: "2.9.6"
  TRIM_GALORE_VERSION: "0.6.6"
  # package variables
  PIP_USE_DEPRECATED: "legacy-resolver"

  # S3MART_JOBS: 32
  S3MART_DATA_DIR: /data

  BPYUTILS_VERBOSE: "true"
  
  # system variables

jobs:
  train:
    name: Train
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/achillesrasquinha/s3mart:base

    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Run Pipeline
        run: |
          bpyutils --run-ml s3mart -p "check=True; data_dir=/data; jobs=32; minimal_output=True"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: /data